octopus:
  # The Octopus server image. Visit https://hub.docker.com/r/octopusdeploy/octopusdeploy for the available versions.
  image: octopusdeploy/octopusdeploy-prerelease:2020.3.0-beta1789.linux
  # Set this to 1 if you do not have a HA license.
  replicaCount: 2
  # The Octopus admin username
  username: admin
  # The Octopus admin password
  password: Password01!
  # The Octopus admin email
  email: admin@example.org
  # Change this, as it is used to encrypt secrets
  masterKey: 6EdU6IWsCtMEwk0kPKflQQ==
  # Must be set to "Y" (including the quotes) to accept the EULA at https://octopus.com/legal/customer-agreement
  acceptEula: "N"
  # Use the MS SQL server defined below
  connectionString: Server=mssql,1433;Database=Octopus;User Id=SA;Password=Password01!
  # The base 64 encoded copy of the Octopus license. This needs to be a HA license if replicaCount is greater than 1.
  licenseKeyBase64:
  # An optional persistent volume claim class name for the Octopus server volumes
  storageClassName:
  # The size of the repository volume
  repositoryVolumeSize: 1Gi
  # The size of the artifact volume
  artifactVolumeSize: 1Gi
  # The size of the task log volume
  taskVolumeSize: 1Gi
  # Settings concerning polling tentacles across the HA nodes
  pollingTenatcles:
    # If true, a load balancer is created for each Octopus instance for polling tentacles to point to.
    # Note that if replicaCount is 1, the load balancer exposing the web interface also exposes port 10943
    # to allow tentacles to connect to the single instance, and this setting should be set to false.
    exposeLoadBalancers: true

dockerHub:
  # Set to true to create a secret containing the docker registry password
  login: false
  # The base 64 encoded Docker config.json file. This value can be created with the command:
  # kubectl create secret docker-registry regcred --docker-username=myusername --docker-password=mypassword --dry-run=client -o yaml
  creds:

mssql:
  # If enabled, a simple MS SQL server will be deployed. Note that this server is not production ready, as it
  # uses ephemeral storage and easily guessed credentials.
  enabled: true
  # This will need to be included in the octopus.connectionString setting
  saPassword: Password01!
  # Must be set to "Y" including quotes to accept the MSSQL EULA
  acceptEula: "N"