kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repository-claim
spec:
  accessModes:
    - {{.Values.octopus.storageAccessMode}}
  {{- if (eq "-" .Values.octopus.storageClassName) }}
  storageClassName: ""
  {{- else if .Values.octopus.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  resources:
    requests:
      storage: {{.Values.octopus.repositoryVolumeSize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifacts-claim
spec:
  accessModes:
    - {{.Values.octopus.storageAccessMode}}
  {{- if (eq "-" .Values.octopus.storageClassName) }}
  storageClassName: ""
  {{- else if .Values.octopus.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  resources:
    requests:
      storage: {{.Values.octopus.artifactVolumeSize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-logs-claim
spec:
  accessModes:
    - {{.Values.octopus.storageAccessMode}}
  {{- if (eq "-" .Values.octopus.storageClassName) }}
  storageClassName: ""
  {{- else if .Values.octopus.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  resources:
    requests:
      storage: {{.Values.octopus.taskVolumeSize}}